#server:
#  servlet:
#    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://ecommerce-backend-ps-db-1:5432/ecommerce-backend
    username: postgres
    password: admin

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

  jackson:
    serialization:
      indent-output: true


  application:
      name: e-commerce

# SMTP Configuration, how spring connects to SMTP
  mail:
    host: localhost
    port: 2525
#    password:
#    username:


encryption:
  salt:
    rounds: 10


jwt:
  algorithm:
    key: SuperSecureKey134!
  issuer: eCommerce
  # expires in one week
  expiryInSeconds: 604800

email:
  from: no-reply@ecommerce.com

app:
  frontend:
    url: http://ecommerce.com



